import { QcAction } from '../index';
declare const MyAxiosRunner001_base: import("..").Constructor<import("..").AxiosRunner<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").QcQueryBuilderMap001, import("..").MakeExtraActionCreatorsType<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").ExtraQueryInfosT1, import("./typesDef001").ExtraActionInfosT1>, import("..").QuerchyDefinition<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").QcQueryBuilderMap001, import("..").MakeExtraActionCreatorsType<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").ExtraQueryInfosT1, import("./typesDef001").ExtraActionInfosT1>>, any, any>>;
export declare class MyAxiosRunner001 extends MyAxiosRunner001_base {
}
declare const MyQuerchy001_base: import("..").Constructor<import("..").Querchy<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").QcQueryBuilderMap001, import("..").MakeExtraActionCreatorsType<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").ExtraQueryInfosT1, import("./typesDef001").ExtraActionInfosT1>, import("..").QuerchyDefinition<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").QcQueryBuilderMap001, import("..").MakeExtraActionCreatorsType<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").ExtraQueryInfosT1, import("./typesDef001").ExtraActionInfosT1>>, any, import("..").QuerchyTypeGroup<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").QcQueryBuilderMap001, import("..").MakeExtraActionCreatorsType<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").ExtraQueryInfosT1, import("./typesDef001").ExtraActionInfosT1>, import("..").QuerchyDefinition<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").QcQueryBuilderMap001, import("..").MakeExtraActionCreatorsType<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").ExtraQueryInfosT1, import("./typesDef001").ExtraActionInfosT1>>, any>>>;
export declare class MyQuerchy001 extends MyQuerchy001_base {
}
declare const MyCacher001_base: import("..").Constructor<import("..").Cacher<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").QcQueryBuilderMap001, import("..").MakeExtraActionCreatorsType<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").ExtraQueryInfosT1, import("./typesDef001").ExtraActionInfosT1>, import("..").QuerchyDefinition<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").QcQueryBuilderMap001, import("..").MakeExtraActionCreatorsType<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").ExtraQueryInfosT1, import("./typesDef001").ExtraActionInfosT1>>, any, import("..").CacherTypeGroup<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").QcQueryBuilderMap001, import("..").MakeExtraActionCreatorsType<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").ExtraQueryInfosT1, import("./typesDef001").ExtraActionInfosT1>, import("..").QuerchyDefinition<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").QcQueryBuilderMap001, import("..").MakeExtraActionCreatorsType<import("./typesDef001").CommonConfig001, import("./typesDef001").QcModelMap001, import("./typesDef001").ExtraQueryInfosT1, import("./typesDef001").ExtraActionInfosT1>>, any>>>;
export declare class MyCacher001 extends MyCacher001_base {
    reduce(action: QcAction, state: any): any;
}
export {};
